# Generic C++ .gitignore template
# Root project name placeholder: {{NAME}}

# Build directories
/build/
/bin/
/lib/
/obj/
/out/
/Debug/
/Release/

# CMake files
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
CMakeLists.txt.user
Makefile
install_manifest.txt
compile_commands.json
*.cmake

# Generated files
*.o
*.obj
*.lo
*.la
*.al
*.libs
*.so
*.so.*
*.dylib
*.dll
*.exe
*.pdb
*.idb
*.class
*.cache
*.ilk
*.meta
*.lib
*.exp
*.app
*.out

# Archives and packages
*.zip
*.tar.gz
*.tar.bz2
*.7z
*.rar

# Backup and temporary files
*~
*.swp
*.swo
*.tmp
*.temp
*.bak
*.orig
*.rej

# IDE/editor directories and files
.vs/
.idea/
*.suo
*.user
*.userosscache
*.sln.docstates
*.vcxproj.user
*.vcxproj.filters
*.ncb
*.opensdf
*.sdf
*.ipch/

# CLion
cmake-build-debug/
cmake-build-release/
cmake-build/

# Qt Creator
*.user
*.user.*
*.pro.user
*.qmake.stash
*.qtc.settings

# Code::Blocks
*.depend
*.layout

# Xcode
*.xcworkspace/
*.xcuserstate
*.xcuserdata/
build/
DerivedData/

# Visual Studio Code
.vscode/
.history/

# macOS
.DS_Store
.AppleDouble
.LSOverride

# Windows
Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/

# Linux
*~
.cache/

# Dependency directories
node_modules/

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Lock files
package-lock.json
yarn.lock

# Generated by build systems
*.dir

# Ignore any file matching project root name placeholder
# {{NAME}}/
